-- Migration 005: Add emagazines, info_publik, tautans tables
-- Tanggal: 2025-04-15

CREATE TABLE IF NOT EXISTS emagazines (
  id        VARCHAR(25)  NOT NULL PRIMARY KEY,
  title     VARCHAR(255) NOT NULL,
  edisi     VARCHAR(100) NOT NULL,
  imageUrl  TEXT         NULL,
  fileUrl   TEXT         NULL,
  isActive  TINYINT(1)   NOT NULL DEFAULT 1,
  `order`   INT          NOT NULL DEFAULT 0,
  createdAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS info_publik (
  id        VARCHAR(25)  NOT NULL PRIMARY KEY,
  title     VARCHAR(255) NOT NULL,
  icon      VARCHAR(10)  NOT NULL DEFAULT '📄',
  url       TEXT         NOT NULL,
  isActive  TINYINT(1)   NOT NULL DEFAULT 1,
  `order`   INT          NOT NULL DEFAULT 0,
  createdAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tautans (
  id        VARCHAR(25)  NOT NULL PRIMARY KEY,
  title     VARCHAR(255) NOT NULL,
  url       TEXT         NOT NULL,
  isActive  TINYINT(1)   NOT NULL DEFAULT 1,
  `order`   INT          NOT NULL DEFAULT 0,
  createdAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
